"""Markdown report generation for the Step 28-31 baselines (Phase A Step 31).

Pure string assembly over already-computed metric frames — no fitting,
predicting, or metric computation happens here, only rendering. Kept
separate from :mod:`fpl.training.baseline` (the models) and
:mod:`fpl.training.evaluation` (the metrics) so each stays independently
testable, mirroring :mod:`fpl.training.eda_report`'s own split.
"""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path

import polars as pl

__all__ = ["render_baseline_report"]


def _markdown_table(frame: pl.DataFrame, *, float_places: int = 4) -> str:
    if frame.height == 0:
        return "_(no rows)_\n"
    header = "| " + " | ".join(frame.columns) + " |"
    separator = "| " + " | ".join("---" for _ in frame.columns) + " |"
    lines = [header, separator]
    for row in frame.iter_rows():
        cells = []
        for value in row:
            if value is None:
                cells.append("")
            elif isinstance(value, float):
                cells.append(f"{value:.{float_places}f}")
            else:
                cells.append(str(value))
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines) + "\n"


def render_baseline_report(
    *,
    train_row_count: int,
    train_seasons: Sequence[str],
    validation_row_count: int,
    validation_season: str,
    naive_metrics: pl.DataFrame,
    glm_metrics: pl.DataFrame,
    points_report: pl.DataFrame,
    gameweek_spearman: pl.DataFrame,
    report_path: Path,
) -> str:
    """Render the full Step 28-30 baseline markdown report as a string.

    ``naive_metrics``: one row per target (``component``, ``mae``, ``rmse``,
    ``n``) — the naive baseline is position-agnostic, so there is no
    per-position breakdown for it.

    ``glm_metrics``: one row per ``(component, position)`` (``mae``,
    ``rmse``, ``poisson_deviance``, ``n``) — ``poisson_deviance`` is null
    for ``minutes`` (Ridge, not a count target).

    ``points_report``: :func:`fpl.training.evaluation.points_error_report`'s
    output — one row for ``"overall"`` plus one per outcome bucket.

    ``gameweek_spearman``:
    :func:`fpl.training.evaluation.spearman_by_gameweek`'s output — summarised
    here as mean/median/min/max over every scored gameweek, since printing
    one row per gameweek across ten seasons would be unreadable.
    """
    spearman_values = gameweek_spearman["spearman"].drop_nulls()
    spearman_summary = pl.DataFrame(
        {
            "gameweeks_scored": [spearman_values.len()],
            "mean_spearman": [spearman_values.mean()],
            "median_spearman": [spearman_values.median()],
            "min_spearman": [spearman_values.min()],
            "max_spearman": [spearman_values.max()],
        }
    )

    sections = [
        "# Phase A baseline evaluation (Steps 28-31)",
        "",
        f"Generated by `fpl baseline`. This file is regenerated from scratch on every "
        f"run — do not hand-edit. Report path: `{report_path.name}`.",
        "",
        "## 1. Split summary",
        "",
        f"- Training split: {train_row_count} row(s) across season(s) "
        f"{', '.join(train_seasons) if train_seasons else '(none)'}.",
        f"- Validation split: {validation_row_count} row(s), season {validation_season}.",
        "- The test split is never read here (plan Step 31's explicit boundary) — it is "
        "reserved for the one-time final read later in Phase A/B.",
        "",
        "## 2. Naive baseline — per-component metrics (validation split)",
        "",
        "Each target's own trailing mean over its most recent fixtures (Step 28), "
        "position-agnostic.",
        "",
        _markdown_table(naive_metrics),
        "## 3. GLM baseline — per-component, per-position metrics (validation split)",
        "",
        "Position-specific Ridge (`minutes`) / Poisson (every other component) pipelines "
        "(Step 29), fit on the training split only.",
        "",
        _markdown_table(glm_metrics),
        "## 4. System score — predicted vs realised total points (validation split)",
        "",
        "Every predicted component (GLM for goals/assists/goals-conceded/bonus/defensive "
        "contribution, naive for saves/cards/penalties/own goals) combined through that "
        "row's own season's scoring ruleset (Step 30). RMSE/MAE overall and within each "
        "outcome bucket (bucketed by the *realised* total — plan Q10).",
        "",
        _markdown_table(points_report),
        "## 5. Rank correlation by gameweek (validation split)",
        "",
        "Spearman rank correlation between predicted and realised total points, computed "
        "within each gameweek's player pool, then summarised across every scored gameweek.",
        "",
        _markdown_table(spearman_summary),
    ]
    return "\n".join(sections) + "\n"
