"""Markdown report generation for the Step 25-26 EDA sweep (Phase A Step 27).

Pure string assembly over an already-computed :class:`fpl.training.eda.EdaResult`
plus the PNG paths :mod:`fpl.training.eda_plots` wrote — no statistics are
computed here, only rendered. Kept separate from both ``eda.py`` (the
statistics) and ``eda_plots.py`` (the figures) so each of the three stays
independently testable: this module's tests build a synthetic
:class:`~fpl.training.eda.EdaResult` directly rather than re-running the
whole sweep.

Every ``|r| > 0.9`` feature pair is listed in full (plan Step 27's explicit
requirement) — nothing else in this report is exhaustive; every other table
is capped at ``top_n`` rows per section, with the section's own total row
count stated in prose so a reader knows what was cut.
"""

from __future__ import annotations

import os
from collections.abc import Mapping, Sequence
from pathlib import Path

import polars as pl

from fpl.training.eda import EdaResult

__all__ = ["render_eda_report"]


def _relative(path: Path, *, report_dir: Path) -> str:
    return os.path.relpath(path, start=report_dir).replace(os.sep, "/")


def _markdown_table(frame: pl.DataFrame, *, float_places: int = 4) -> str:
    if frame.height == 0:
        return "_(no rows)_\n"
    header = "| " + " | ".join(frame.columns) + " |"
    separator = "| " + " | ".join("---" for _ in frame.columns) + " |"
    lines = [header, separator]
    for row in frame.iter_rows():
        cells = []
        for value in row:
            if value is None:
                cells.append("")
            elif isinstance(value, float):
                cells.append(f"{value:.{float_places}f}")
            else:
                cells.append(str(value))
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines) + "\n"


def _top_n(frame: pl.DataFrame, *, n: int) -> pl.DataFrame:
    return frame.head(n)


def render_eda_report(
    result: EdaResult,
    *,
    train_row_count: int,
    train_seasons: Sequence[str],
    curated_columns: Sequence[str],
    histogram_paths: Sequence[Path],
    target_distribution_paths: Mapping[str, Path],
    correlation_heatmap_paths: Mapping[str, Path],
    missingness_path: Path,
    report_path: Path,
    top_n: int = 15,
) -> str:
    """Render the full Step 25-27 markdown report as a string.

    ``report_path`` is only used to compute image paths relative to where the
    report itself will be written — the caller still does the actual
    ``write_text``."""
    report_dir = report_path.parent
    sections: list[str] = []

    sections.append(
        "# Model prototype: exploratory data analysis\n\n"
        "Generated by `fpl eda` (Phase A Steps 25-27). Every statistic below is "
        f"computed **on the chronological training split only** ({', '.join(train_seasons)}), "
        f"{train_row_count} row(s) — validation and test are never touched here, so nothing "
        "in this report has seen data the eventual model selection is meant to be blind to.\n"
    )

    kind_counts = result.column_kinds.group_by("kind").len().sort("kind")
    sections.append(
        "## 1. Feature type classification\n\n"
        "Every column is one of five kinds: `identifier` (never a feature), `categorical` "
        "(nominal — `position`, `team_code`, `opponent_team_code`), `boolean` (`was_home` and "
        "the four `obs_*` era masks), `label` (the 13 prediction targets), or `numeric` (every "
        "rolling-window and team-context feature — the only kind the variance, skew, outlier, "
        "correlation, VIF and mutual-information sections below cover).\n\n"
        f"{_markdown_table(kind_counts)}\n"
    )

    total_missing_cols = result.missing.filter(pl.col("null_fraction") > 0).height
    worst_missing = result.missing.sort("null_fraction", descending=True)
    sections.append(
        "## 2. Missing values\n\n"
        f"{total_missing_cols} of {result.missing.height} column(s) have at least one null. "
        "Most missingness here is structural, not accidental: a numeric feature governed by an "
        "`obs_*` era mask (e.g. defensive-contribution stats, only recorded from 2023-24) is null "
        "for every row from a season before that stat existed, and the `_last_season`/"
        "`season_to_date` rolling windows are null for a player's first-ever recorded fixture "
        "(there is no history yet to roll over) — both are expected, not a data bug. The era "
        "breakdown below is an approximation: it uses each row's own `obs_*` flag as a proxy for "
        "the governing era, since a rolling window can straddle an era boundary.\n\n"
        f"Top {top_n} columns by null fraction:\n\n"
        f"{_markdown_table(_top_n(worst_missing, n=top_n))}\n"
    )

    sections.append(
        "## 3. Cardinality\n\n"
        "`n_unique` for every `identifier`/`categorical`/`boolean` column — the kinds an "
        "encoding decision applies to.\n\n"
        f"{_markdown_table(result.cardinality)}\n"
    )

    near_zero = result.variance.filter(pl.col("near_zero_variance"))
    sections.append(
        "## 4. Variance and near-zero-variance\n\n"
        f"{near_zero.height} of {result.variance.height} numeric feature(s) are flagged "
        "near-zero-variance. Nothing is dropped here — this is a candidate list for later "
        "feature-selection judgement, not an automatic exclusion.\n\n"
        f"{_markdown_table(near_zero) if near_zero.height else '_(none flagged)_'}\n"
    )

    most_skewed = result.distribution.with_columns(
        pl.col("skewness").abs().alias("_abs_skew")
    ).sort("_abs_skew", descending=True)
    sections.append(
        "## 5. Skewness and kurtosis\n\n"
        f"Top {top_n} numeric feature(s) by absolute skewness (of "
        f"{result.distribution.height} total):\n\n"
        f"{_markdown_table(_top_n(most_skewed, n=top_n).drop('_abs_skew'))}\n"
    )

    outlier_summary = result.outliers.sort("iqr_outlier_fraction", descending=True)
    sections.append(
        "## 6. Outliers\n\n"
        "Both an IQR (x1.5) and a z-score (|z| > 3) rule are reported side by side — neither "
        "supersedes the other, both are informative for a skewed count-like feature.\n\n"
        f"Top {top_n} numeric feature(s) by IQR outlier fraction:\n\n"
        f"{_markdown_table(_top_n(outlier_summary, n=top_n))}\n"
    )

    heatmap_links = "\n".join(
        f"- [{name} correlation heatmap]({_relative(path, report_dir=report_dir)})"
        for name, path in correlation_heatmap_paths.items()
    )
    sections.append(
        "## 7. Correlation matrices and high-correlation pairs\n\n"
        f"Pearson and Spearman correlation are computed pairwise-complete over every numeric "
        f"feature ({result.pearson.height} columns); list-wise-complete would drop nearly the "
        "whole training set, since early-history rows are systematically null across many "
        "columns at once.\n\n"
        f"{heatmap_links}\n\n"
        f"**Every `|r| > 0.9` feature pair, flagged and not dropped** "
        f"({result.high_correlation_pairs.height} pair(s)):\n\n"
        f"{_markdown_table(result.high_correlation_pairs)}\n"
    )

    sections.append(
        "## 8. Variance inflation factor (VIF)\n\n"
        f"Computed over a curated, non-redundant column subset ({len(curated_columns)} "
        "column(s) — one representative window per underlying stat, since a full VIF over "
        "every mutually-derived rolling-window column is computationally infeasible and mostly "
        "redundant with the correlation-pair flags above):\n\n"
        f"{_markdown_table(result.vif)}\n"
    )

    mi_by_target: list[str] = []
    for target in sorted(result.mutual_information["target"].unique().to_list()):
        target_mi = (
            result.mutual_information.filter(pl.col("target") == target)
            .sort("mutual_information", descending=True)
            .drop("target")
        )
        mi_by_target.append(f"### {target}\n\n{_markdown_table(_top_n(target_mi, n=top_n))}\n")
    sections.append(
        "## 9. Mutual information against each target\n\n"
        "Catches non-linear relationships a correlation coefficient misses. "
        f"Top {top_n} feature(s) per target:\n\n" + "\n".join(mi_by_target)
    )

    corr_by_target: list[str] = []
    for target in sorted(result.target_correlation["target"].unique().to_list()):
        target_corr = result.target_correlation.filter(pl.col("target") == target).drop("target")
        corr_by_target.append(f"### {target}\n\n{_markdown_table(_top_n(target_corr, n=top_n))}\n")
    sections.append(
        "## 10. Target-correlation rankings\n\n"
        f"Pearson and Spearman correlation, sorted by descending `|pearson_r|`. "
        f"Top {top_n} feature(s) per target:\n\n" + "\n".join(corr_by_target)
    )

    hist_links = "\n".join(
        f"- [{path.stem}]({_relative(path, report_dir=report_dir)})" for path in histogram_paths
    )
    target_links = "\n".join(
        f"- [{target}]({_relative(path, report_dir=report_dir)})"
        for target, path in target_distribution_paths.items()
    )
    sections.append(
        "## 11. Figures\n\n"
        f"**Feature histograms** ({len(curated_columns)} curated column(s)):\n\n"
        f"{hist_links}\n\n"
        "**Target distributions**, zeros/blanks/tickers/haulers outcome buckets shaded:\n\n"
        f"{target_links}\n\n"
        f"**Missingness by season**: "
        f"[missingness_by_season]({_relative(missingness_path, report_dir=report_dir)})\n"
    )

    return "\n".join(sections)
